# **Lidando com exceções**

## **Tipos de erros em destaque**

### **Sintaxe**

* Ocorrem ao utilizar recursos que não existem.

~~~py
print("Olá, mundo!") # Código no padrão Python
print{"Olá, mundo!"} # Gera erro de sintaxe
~~~

### **Exceções**

* Ocorrem durante a execução e retornam mensagens de erro.

~~~py
print(10 * (1 / 0))
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ZeroDivisionError: division by zero
print(4 + spam * 3)
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# NameError: name 'spam' is not defined
print('2' + 2)
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# TypeError: can only concatenate str (not "int") to str
~~~

> Lista completa de exceções: <https://docs.python.org/pt-br/3/library/exceptions.html#bltin-exceptions>

## **Tratamento de exceções**

### **try/except**

* Na ausência de exceções, o `try` é executado e o `except` é ignorado;
* Se ocorrer uma exceção durante o `try` e o `except` prever o tipo, ele será executado;
* Sem tratamento para o tipo de exceção, o programa termina com uma mensagem de erro.

~~~py
while True:
    try:
        x = int(input("Please enter a number: "))
        break
    except ValueError:
        print("Oops!  That was no valid number.  Try again...")
~~~

## **Lidando com exceções ao manipular arquivos**

### **else/finally**

* `finally` executa sempre e tem a finalidade de implementar ações de limpeza;
* `else` executa apenas se o `try` não gerar exceção.

~~~py
try:
    arquivo = open("arquivo.txt", "r")
except OSError:
    # Executado no caso de exceção
    print("arquivo inexistente")
else:
    # Executado se tudo ocorrer bem no try
    print("arquivo manipulado e fechado com sucesso")
    arquivo.close()
finally:
    # Sempre executado, independente de exceções
    print("Tentativa de abrir arquivo")
~~~

> Como o modo é leitura, uma exceção será gerada se o arquivo não existir. Se fosse escrita, o arquivo seria criado mesmo se não existisse, não gerando exceção.

### **with**

* Encapsula a ação de um recurso, garantindo a execução de um bloco de código, independente de exceções;
* A função `open` retorna um objeto gerenciador de contexto, que abre um arquivo e fecha quando o bloco de código termina.

~~~py
# Cria-se um contexto, limitando o escopo onde o arquivo está aberto.
# O uso do "as" aqui é somente para atribuir o valor utilizado no contexto à variável file
with open("arquivo.txt", "w") as file:
    file.write("Michelle 27\n")
# como estamos fora do contexto, o arquivo foi fechado
print(file.closed)
~~~
